#!/usr/bin/python3 

import open_url
import datetime as dt
import clipboard

if __name__ == "__main__":

    today = dt.datetime.today()
    today_string = today.strftime ( "%Y-%m-%d [%A]" )
    print("Today's Date: {}".format ( today_string ) )
    clipboard.copy ( today_string )
    
    open_url.run ( url='https://www.evernote.com/client/web?login=true#?hm=true&', browser='firefox' )
